const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (fn) => ipcRenderer.on(channel, (_e, payload) => fn(payload));

contextBridge.exposeInMainWorld('pet', {
  init: () => ipcRenderer.invoke('pet:init'),
  setInteractive: (v) => ipcRenderer.send('mouse:interactive', v),
  dragPress: () => ipcRenderer.send('drag:press'),
  dragStart: () => ipcRenderer.send('drag:start'),
  dragEnd: () => ipcRenderer.invoke('drag:end'),
  layout: (geo) => ipcRenderer.invoke('win:layout', geo),
  hideWindow: () => ipcRenderer.send('win:hide'),
  contextMenu: () => ipcRenderer.send('menu:context'),
  send: (text) => ipcRenderer.invoke('ai:send', text),
  cancel: () => ipcRenderer.send('ai:cancel'),
  onToken: on('ai:token'),
  onCharacter: on('pet:character'),
  onRenamed: on('pet:renamed'),
  onVisibility: on('pet:visibility'),
  onChatReset: on('chat:reset'),
  onUpdateAvailable: on('update:available'),
  onUpdateStatus: on('update:status'),
  updateSeen: (version) => ipcRenderer.send('update:seen', version),
  timer: {
    status: () => ipcRenderer.invoke('timer:status'),
    action: (action) => ipcRenderer.send('timer:action', action),
    remark: (info) => ipcRenderer.invoke('timer:remark', info),
    onStatus: on('timer:status'),
    onEnd: on('timer:end'),
    onSound: on('timer:sound'),
  },
  claude: {
    status: () => ipcRenderer.invoke('claude:status'),
    onStatus: on('claude:status'),
    dismiss: () => ipcRenderer.send('claude:dismiss'),
    open: () => ipcRenderer.send('claude:open'),
    reconnect: () => ipcRenderer.send('claude:reconnect'),
    onState: on('settings:claude-code'),
  },
  // Pet window -> balloon window (via main).
  bubble: (content) => ipcRenderer.send('bubble:content', content),
  bubbleShow: (opts) => ipcRenderer.send('bubble:show', opts),
  bubbleHide: () => ipcRenderer.send('bubble:hide'),
  onBubbleSubmit: on('bubble:submit'),
  onBubbleTyping: on('bubble:typing'),
  onBubbleEscape: on('bubble:escape'),
  onBubbleClick: on('bubble:click'),
  // Used inside the balloon window.
  balloon: {
    onContent: on('bubble:content'),
    onPlace: on('bubble:place'),
    onOpen: on('bubble:open'),
    onFocus: on('bubble:focus'),
    onTheme: on('bubble:theme'),
    size: (h) => ipcRenderer.send('bubble:size', h),
    submit: (text) => ipcRenderer.send('bubble:submit', text),
    typing: () => ipcRenderer.send('bubble:typing'),
    escape: () => ipcRenderer.send('bubble:escape'),
    click: () => ipcRenderer.send('bubble:click'),
  },
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (patch) => ipcRenderer.send('settings:set', patch),
  fitSettings: (fit) => ipcRenderer.send('settings:fit', fit),
  onSettings: on('settings:changed'),
  onSettingsTab: on('settings:tab'),
  characters: {
    choose: () => ipcRenderer.invoke('characters:choose'),
    prepare: (file) => ipcRenderer.invoke('characters:prepare', file),
    add: (name) => ipcRenderer.invoke('characters:add', name),
    cancel: () => ipcRenderer.send('characters:cancel'),
    rename: (id, name) => ipcRenderer.send('characters:rename', id, name),
    remove: (id) => ipcRenderer.invoke('characters:delete', id),
    copyPrompt: () => ipcRenderer.send('characters:copy-prompt'),
    onChange: on('settings:characters'),
  },
  auditCharacters: () => ipcRenderer.invoke('audit:characters'),
  selftest: {
    log: (line) => ipcRenderer.send('selftest:log', line),
    capture: (name) => ipcRenderer.invoke('selftest:capture', name),
    done: (code) => ipcRenderer.send('selftest:done', code),
    geometry: () => ipcRenderer.invoke('selftest:geometry'),
  },
});
